name: architecture_template
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  flutter_riverpod: 2.0.2
  get_it: 7.2.0
  flutter_screenutil: 5.5.4
  retrofit: 3.3.1
  json_annotation: 4.7.0
  dio: 4.0.6
  freezed_annotation: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  dart_code_metrics: 4.21.2
  build_runner: 2.3.2
  mockito: 5.3.2
  retrofit_generator: 4.2.0
  json_serializable: 6.5.3
  freezed: 2.2.0

flutter:
  uses-material-design: true
  generate: true
